trivyOperator:
  scanJobPodTemplatePodSecurityContext:
    RunAsUser: 10000
    RunAsGroup: 10000
    RunAsNonRoot: true
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true

operator:
  clusterSbomCacheEnabled: true
  scanJobsConcurrentLimit: 1
  scannerReportTTL: "336h"
serviceMonitor:
  enabled: true
trivy:
  ignoreUnfixed: true

nodeCollector:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  volumeMounts:
    - name: var-lib-etcd
      mountPath: /var/lib/etcd
      readOnly: true
    - name: var-lib-kubelet
      mountPath: /var/lib/kubelet
      readOnly: true
    - name: var-lib-kube-scheduler
      mountPath: /var/lib/kube-scheduler
      readOnly: true
    - name: var-lib-kube-controller-manager
      mountPath: /var/lib/kube-controller-manager
      readOnly: true
    - name: etc-kubernetes
      mountPath: /etc/kubernetes
      readOnly: true
    - name: etc-cni-netd
      mountPath: /etc/cni/net.d/
      readOnly: true
# resources:
#   requests:
#     cpu: 25m
#     memory: 750Mi

