apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: cloudflare-api-token
  namespace: <cert-manager-namespace>
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: https://<infisical-host>/api
  resyncInterval:
  authentication:
     universalAuth:
      credentialsRef:
        secretName: <infisical-credentials-secret-name>
        secretNamespace: <infisical-namespace>
      secretsScope:
        projectSlug: <infisical-project-slug>
        envSlug: <infisical-environment-slug>
        secretsPath: "<infisical-secrets-path>"
  managedSecretReference:
    secretName: cloudflare-api-token-secret
    secretNamespace: <cert-manager-namespace>
